[global]
   server role = standalone server
   workgroup = WORKGROUP
   interfaces = lo @@CONTAINER_IP@@/24
   bind interfaces only = yes
   hosts allow = 127. 10.10.10. 100.64.0.0/10
   hosts deny = 0.0.0.0/0
   server min protocol = SMB3
   server signing = mandatory
   smb encrypt = required
   map to guest = never
   disable netbios = yes
   smb ports = 445
   logging = systemd

[zerofs]
   path = /srv/zerofs-share/data
   browseable = yes
   read only = no
   guest ok = no
   valid users = @@SAMBA_USER@@
   force user = @@SAMBA_USER@@
   create mask = 0660
   directory mask = 0770
